language: python

python:
  - 3.4

before_script:
  - flake8 tests ogn

script:
  - nosetests --with-coverage --cover-package=ogn

  - pip install . --upgrade
  - python -c 'import ogn'

after_success:
  - coveralls
